{% set name = "retryhttp" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/retryhttp-{{ version }}.tar.gz
  sha256: 071a0296ac69640f9685cc96f9e259c155d327943cc2d15b827eea7577976178

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=21.0.0,!=24.0.0,!=34.0.0,!=34.0.1,!=34.0.2,!=34.0.3,!=34.1.0,!=34.1.1,!=34.2.0,!=34.3.0,!=34.3.1,!=34.3.2,!=36.2.0
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - httpx
    - pydantic
    - requests
    - types-requests
    - tenacity

test:
  imports:
    - retryhttp
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/austind/retryhttp
  summary: Retry potentially transient HTTP errors in Python.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/austind/retryhttp
  doc_url: https://retryhttp.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
